import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { AgentSelector } from "@/pages/components/Document/components/AgentSelector";

interface Agent {
  id: string;
  name: string;
  type: string;
  description: string;
  avatar?: string;
  capabilities: string[];
}

const agents: Agent[] = [
  {
    id: '1',
    name: 'Legal Expert AI',
    type: 'legal',
    description: 'Specializes in legal document generation and review.',
    capabilities: ['Contract Drafting', 'Compliance Check', 'Legal Research']
  },
  {
    id: '2',
    name: 'Marketing Content AI',
    type: 'marketing',
    description: 'Generates engaging marketing content for various platforms.',
    capabilities: ['Ad Copy', 'Blog Posts', 'Social Media Content']
  },
  {
    id: '3',
    name: 'Technical Writer AI',
    type: 'technical',
    description: 'Creates clear and concise technical documentation.',
    capabilities: ['User Manuals', 'API Docs', 'Troubleshooting Guides']
  }
];

export const DocumentGenerator = () => {
  const [documentName, setDocumentName] = useState('');
  const [templateData, setTemplateData] = useState({
    title: '',
    content: ''
  });
  const [generatedDocument, setGeneratedDocument] = useState('');
  const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null);

  const handleGenerateDocument = () => {
    if (!selectedAgent) {
      alert('Please select an AI Agent.');
      return;
    }

    // Simulate AI document generation based on selected agent and template data
    const generatedContent = `
      # ${templateData.title}

      Generated by ${selectedAgent.name}:

      ${templateData.content}
    `;

    setGeneratedDocument(generatedContent);
  };

  return (
    <div className="container mx-auto p-6 space-y-6">
      <div className="text-center">
        <h1 className="text-3xl font-bold mb-4">AI Document Generator</h1>
        <p className="text-gray-500">
          Generate professional documents quickly using AI-powered templates.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Select AI Agent</CardTitle>
              <CardDescription>
                Choose an AI agent specialized for your document type
              </CardDescription>
            </CardHeader>
            <CardContent>
              <AgentSelector
                agents={agents}
                selectedAgent={selectedAgent}
                onAgentChange={setSelectedAgent}
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Document Details</CardTitle>
              <CardDescription>
                Enter the details for your document
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="document-name">Document Name</Label>
                <Input
                  id="document-name"
                  placeholder="Enter document name"
                  value={documentName}
                  onChange={(e) => setDocumentName(e.target.value)}
                />
              </div>
              <div>
                <Label htmlFor="template-title">Template Title</Label>
                <Input
                  id="template-title"
                  placeholder="Enter template title"
                  value={templateData.title}
                  onChange={(e) => setTemplateData({ ...templateData, title: e.target.value })}
                />
              </div>
              <div>
                <Label htmlFor="template-content">Template Content</Label>
                <Textarea
                  id="template-content"
                  placeholder="Enter template content"
                  value={templateData.content}
                  onChange={(e) => setTemplateData({ ...templateData, content: e.target.value })}
                />
              </div>
            </CardContent>
          </Card>

          <Button onClick={handleGenerateDocument}>Generate Document</Button>
        </div>

        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Generated Document</CardTitle>
              <CardDescription>
                Preview of the generated document
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Textarea
                placeholder="Generated document will appear here"
                value={generatedDocument}
                readOnly
                className="min-h-[300px]"
              />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};
